### PR TITLE
Support zstd compressed metadata

### LINKED ISSUE #96: Support zstd compression
createrepo_c is adding support for zstd-compressed metadata, which has a lot of benefits. I intend to push for this to be used by Fedora eventually.

(I'll submit a PR for this later, it should be very easy to add)

### PR DESCRIPTION
**Pull request by dralley**
closes #96

### CODE REVIEW

**Comment by dralley** [comment]
@t0xic0der Re-pushed

**Comment by gridhead** [comment]
@dralley,

Some tests are still failing.
Please feel free to add tests that satisfy the conditions you have introduced, if the current tests do not quite match.

**Comment by dralley** [comment]
@t0xic0der Not so much that the tests were failing as that the lockfile was messed up and they weren't being run :)

**Comment by dralley** [comment]
There aren't any tests for the existing alternate compression types so I'm not really sure what to add - it appears that the tests run against the fedora mirrors directly and would use whichever compression those specific repos use.

**Review by gridhead — APPROVED** [review]
Looks like all the checks are turning green.

The changes are very minimal but I have one nitpick around importing `pyzstd` in between rather than with every other import in the code at the top of the file. Please help me understand what difference this makes.

I would wait on your response https://github.com/fedora-infra/mdapi/issues/96#issuecomment-1447566303 before I do something about the PR.

**Comment by dralley** [comment]
>The changes are very minimal but I have one nitpick around importing pyzstd in between rather than with every other import in the code at the top of the file. Please help me understand what difference this makes.

It doesn't make a difference - it could easily be moved up to the top for consistency if you wish.

**Pull request merged**
