### PR TITLE
[WIP] Demonstrate wrong Node.js SRPM version.

### PR DESCRIPTION
**Pull request by voxik**
This is just attempt to update the test case to demonstrate issues with Node.js as mentioned in #58. Not sure how to make better test case. Iterating over the whole DB content would probably be quite slow.

### CODE REVIEW

**Comment by voxik** [comment]
BTW sorry, but I don't plan ATM to bring this any further then providing the reproducer in this minimal form.

**Comment by gridhead** [comment]
That is totally fine. Any and every assistance is appreciated :)

**Comment by gridhead** [comment]
@voxik, any updates on this?

**Comment by voxik** [comment]
> @voxik, any updates on this?

Sorry no. I don't plan to work on this issue any further.

**Pull request closed without merging**
