### PR TITLE
Add epel9 release

### PR DESCRIPTION
**Pull request by humaton**
Adds epel9 to the database scripts

### CODE REVIEW

**Comment by gridhead** [comment]
Looks good to me. 

`https://dl.fedoraproject.org/pub/epel/9/Everything/x86_64/` is a resource that exists.

I will prolly deploy these changes in the next version release on the staging environment first before these come to the production environment, so it would take some time.

**Review by gridhead — APPROVED** [review]

**Comment by avylove** [comment]
Just wondering why this was done this way rather than update the existing conditional to ``elif rels["name"] == "Fedora EPEL" and versdata >= "8"``. Is there an expectation that 10 will be different?

**Comment by carlwgeorge** [comment]
As a matter of fact, EPEL 10 is going to work differently.

https://discussion.fedoraproject.org/t/epel-10-proposal/44304

**Comment by richardfearn** [comment]
> I will prolly deploy these changes in the next version release on the staging environment first before these come to the production environment, so it would take some time.

@gridhead Seems to work well in staging! How do you normally go about doing these releases? Will there be an issue/ticket somewhere for the prod deployment?

**Comment by gridhead** [comment]
Hi @richardfearn, I let the staging deployment stay on the counter for a week to see if anyone raises complains about it. In case there are no complains - which usually is the case, the deployment identical to the staging deployment is made on the production.

I do not think I have documented this somewhere but there is a deployment SOP.

**Pull request merged**
